In [242]:
# yield_of_apple= w1*temperature + w2*rainfall + w3*humidity       let w1 w2 w3 are weights variable , for annual yield we made a linear relationship between avg temp rainf humidity

In [243]:
w1 , w2 , w3 = 0.3 , 0.2 , 0.5

In [244]:
weights = [w1, w2, w3]

In [245]:
kanto = [73, 67, 43]
jhoto = [91, 88, 64]
hoenn = [87, 134, 58]         #these are avg temp(F) , rainfall(mm) , humidity(%)
sinnoh = [102, 43, 37]         # these are represented in vector form 
unova = [69, 96, 70]

In [246]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):        #observe its a function we made for cross product i.e  m=a,b,c   n=x,y,z      dot product  m*n=ax + by +cz
        result += x*w
    return result

In [247]:
crop_yield(kanto, weights)         #result is of dot multiply

56.8

In [248]:
#numpy library used in performing numerical data 
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [249]:
import numpy as np

In [250]:
kanto = np.array([73,67,43])
print(kanto)

[73 67 43]


In [251]:
weights = np.array([w1, w2, w3])
print(weights)

[0.3 0.2 0.5]


In [252]:
type(kanto)
type(weights)      #now they are no longer the python list they became a special datatype numoy arrays offered by numpy but it my behave like list for eg id ask for notation start from 0,1,2..... index

numpy.ndarray

In [253]:
np.dot(kanto, weights)       # direct way to dot product of vectors.

np.float64(56.8)

In [254]:
# now numpy arrays have special way of doing airthmatic operations
print(kanto) 
print(weights)

[73 67 43]
[0.3 0.2 0.5]


In [255]:
kanto*weights   #it does eliment wise multiplication of 2 vectors

array([21.9, 13.4, 21.5])

In [256]:
(kanto*weights).sum()     # now .sum() will add those elements so, another way of dot product , look how easy numpy does this for us. also it is much faster u check using %%time 

np.float64(56.8)

In [257]:
#lets check the differnce in time , and how it is fast 
arr1 = list(range(1000000))  # 0 to 1 million
arr2 = list(range(1000000,2000000)) #1 mil to 2 mil         a normal python list

arr1 = np.array(arr1)
arr2 = np.array(arr2)     # here are numpy arrays

In [258]:
%%time
#for checking python
result= 0
for (x1,x2) in zip(arr1,arr2):
    result += x1*x2
print(result)

833332333333500000
CPU times: total: 250 ms
Wall time: 260 ms


In [259]:
%%time
#now checking numpy time
np.dot(arr1,arr2)            #wooh 100x times faster

CPU times: total: 0 ns
Wall time: 1.47 ms


np.int64(833332333333500000)

In [260]:
# numpy has miltiple dimension array
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [261]:
climate_data.shape     # check the result and therefore it is a 2D array and previous we were taking only kanto so that was 1D array

(5, 3)

In [262]:
# 3D array
arr3 = np.array([
            [[11, 12, 13],
             [13, 14, 15]],
                                                # check the screenshot , its like a minecraft block , in the code upper one a matrix sheet and the lower is also a matrix sheet just stacked behind like adding two pages of copy 
            [[15, 16, 17],
             [17, 18, 19.5]]]) 

In [263]:
arr3.shape      # starts with outer most no. of matrix (or height)=2 , then no. of rows(length)=3 , columns=3

(2, 2, 3)

1D: [1, 2, 3] → one line <br>
2D: [[1,2,3], [4,5,6]] → a matrix/sheet <br>
3D: several 2D matrices stacked → a stack of sheets <br>
4D: several 3D stacks grouped together → a collection of stacks <br>

In [264]:
#4D array
shape = (2,3,4,5)     # two 3D arrays combine , 3 matrix sheets , 4 rows in each , 5 columns in each.
#similary 5D will contain more no. of 4D structure in it depends on how many we want
# ahhh its complex bro but dont focus more now

In [265]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [266]:
weights

array([0.3, 0.2, 0.5])

In [267]:
#now lets suppose climate data as a matrix and weights as another matrix
crop_yield = np.matmul(climate_data, weights)        #doing matrix multiplication , 5x3 3x1 = 5x1
# another and easy way of doing matrix mutiplication is 
crop_yield = climate_data @ weights    # easy way of doing matrix multiplication only for numpy arrays

In [268]:
crop_yield  # here we get the yield of all above 5 regions using the above formula

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [269]:
import urllib.request 
url = "https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/rowscolumns.csv"                            # we have csv file in downloaded , so cant paste the url here we either have to post it on any internet to get the url maybe in github or other but for downloaded csv we genrally use pandas,,,,                                                   # we have csv file in downloaded , so cant paste the url here we either have to post it on any internet to get the url maybe in github or other but for downloaded csv we genrally use pandas,,,,
urllib.request.urlretrieve (url,'climate.txt')   # let name of the file (climate.txt)                                      

('climate.txt', <http.client.HTTPMessage at 0x201f861d7f0>)

In [270]:
#now lets make that csv file into numpy array
climate_data = np.genfromtxt('climate.txt ', delimiter=',' ,skip_header=1)  #delimiter means thats the numbers are separated with comma , skip_header is to skip the 1st line of csv file having headline that this row is temparature rainfall humidity.

In [271]:
climate_data.shape    # the output would be (10000,3)

(10000, 3)

In [272]:
yields = climate_data @ weights   # note:  weights = np.array([0.3, 0.2, 0.5])
# here we get our yield from all the 10k regions knowing there temp rainfall and humidity. now we want to add the yield of that region in front of em in csv file as 4th column. as this yield answer we get here will be of 10k rows and single column answer .

In [273]:
yields

array([509.3, 648. , 266.4, ..., 583.8, 783.9, 668.6], shape=(10000,))

In [274]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)),axis = 1 )  # here axis one indicated to add that yiels result is added in column as shape starts from height row column in 3d , but here its a 2d so row = axis 0 and column = axis 1

In [275]:
climate_results           # if u check  climate_results.shape , output will be (10k,4)

array([[ 90. , 774. , 655. , 509.3],
       [439. , 434. , 859. , 648. ],
       [ 86. , 698. , 202. , 266.4],
       ...,
       [875. , 154. , 581. , 583.8],
       [992. , 114. , 927. , 783.9],
       [304. , 742. , 858. , 668.6]], shape=(10000, 4))

In [276]:
np.savetxt('climate.txt',
           climate_results,
           fmt='%.2f',                        #for taking results upto 2 deciaml points
           header='temperature,rainfall,himidity, yield_apple',       #headings
           comments='')

In [277]:
'''
 Mathematics: np.sum, np.exp, np.round, arithemtic operators
 Array manipulation: np.reshape, np.stack, np.concatenate, np.split
 Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
 Statistics: np.mean, np.median, np.std, np.max
'''

'\n Mathematics: np.sum, np.exp, np.round, arithemtic operators\n Array manipulation: np.reshape, np.stack, np.concatenate, np.split\n Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals\n Statistics: np.mean, np.median, np.std, np.max\n'

In [278]:
#learning airthmetic operations on arrays 

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],             #think it like a matrix sheet , 2D array , 3 rows and 4 columns
                 [9,1,2,3]])

In [279]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]])

In [280]:
arr2 + arr3         #element wise addition , like it like matrix addition 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [281]:
#adding a scalar 
arr2 + 3              #each element of arr2 will be added with 3 , like a matrix addition with a scalar value

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [282]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [283]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [284]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [285]:
arr2 % 4  #reminder

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [286]:
arr4 = np.array([1,2,3,4])  

In [287]:
arr2 + arr4         # numpy will automatically broadcast and replicate the arr4 and add 2 more same rows to match the shape of arr2 for addition. arr4 will become like [[1,2,3,4],[1,2,3,4],[1,2,3,4]].                                                                                                                                                                       

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10,  3,  5,  7]])

In [288]:
#note the broadcasting will only work if the shape of array with able to match the shape of other array by replication 
arr5 = np.array([1,2,3])  # after broadcasting arr5 will not able to match the shape of arr2, arr2.shape is (3,4) and after broadcasting arr5 will become (3,3) so it will not work for addition or any other operation with arr2.
arr5 + arr2

ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [ ]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,5]])

In [ ]:
arr1 == arr2        # the result will give the arrays of boolean 

In [ ]:
arr1 >= arr2 

In [ ]:
(arr1 == arr2).sum()   # true=1   false=0   so the sum will give the no. of true values in the array

In [ ]:
arr3= np.array([
    [[1, 2, 1, 2], [3, 4, 3, 4]],
    [[5, 6, 5, 6], [7, 8, 7, 8]],
    [[9, 10, 9, 10], [11, 12, 11, 12]]
])

In [ ]:
arr3.shape

In [ ]:
arr3[1,1,2]   # typo range thing like starting from 0,1,2... index also first no the select the outer matrix , then rows and then column. [a,b,c] a will select the outer matrix, b will select the which rows to keep and then c with decide the which column to keep and that will give us our final answer.

In [ ]:
arr3[1:, 0:1 , :2]   # 0,1,2... indexing

In [ ]:
arr3[1:, 1, 3]

In [ ]:
arr3[:2,1]

In [ ]:
#now lets make a numpy array
np.zeros((3,2))   # it will create a 3x2 matrix with all elements as 0

In [ ]:
np.ones((3,3))    # it will create a 3x3 matrix with all elements as 1  

In [ ]:
np.ones((2,2,3))    # it will create 2 matrix bunch together of 2x3

In [ ]:
#identity matrix
np.eye(3)

In [ ]:
# 3 random vector
np.random.rand(3)

In [ ]:
# random metrix
np.random.rand(3,2) #no tuple entry like ((3,2))  # also instead of .rand we can write .randn for normal distribution and .rand for uniform distribution

In [ ]:
np.random.randn(2,3)    #randn will take nos. from [-2,2] generally

In [ ]:
#fixed value
np.full((2,3), 49)

In [ ]:
np.arange(10,90,3)   #arange is the analog of range

In [ ]:
np.arange(10,90,3).shape #no. of element in our array

In [ ]:
# no since the no of array is 27 therefore we can make a 3 matrix of 3x3, or 1x27, or 3x9. but its too complex to check it so we can also write (3,3,-1),or let supoose we wanna create 3 matrix of 3 fixed column and there can be many rows based on amount of data so we can write (3,-1,3)
np.arange(10,90,3).reshape(3,3,3)

In [ ]:
# let suppose we want to make 9 elements from no. 2 to 46 
np.linspace(2,46,9)   # and thus it will give me equally spaced 9 arrays btw 2 and 46

In [ ]:
np.arange(10,90,3).reshape(3, -1, 3)

In [ ]:
arr1 = np.array(
    [[1,2],[3,4]])
arr2= np.array(
    [[5,6,7],[8,9,10]])
arr3=np.concatenate((arr1, arr2), axis=1)  # axis is like index , axis=1 means we are concatenating along the columns, so the resulting array will have the same number of rows as arr1 and arr2, but the number of columns will be the sum of the columns of arr1 and arr2.
arr3

In [ ]:
arr4= np.mean(arr3)    #mean sum of all/ total elements = 55/10
arr4

In [291]:
import os

In [290]:
os.getcwd()

'c:\\Users\\poona\\OneDrive\\Documents\\Desktop\\jupyter notebook'

In [292]:
os.listdir('.')    #relative path of current working directory, it will give the list of all files in the current working directory

['.ipynb_checkpoints',
 'climate.txt',
 'data',
 'jupyter 1 ,basic python.ipynb',
 'jupyter 2 , start with numpy.ipynb',
 'new_file',
 'new_folder']

In [293]:
os.listdir()

['.ipynb_checkpoints',
 'climate.txt',
 'data',
 'jupyter 1 ,basic python.ipynb',
 'jupyter 2 , start with numpy.ipynb',
 'new_file',
 'new_folder']

In [294]:
os.makedirs('./data', exist_ok=True)   #it will create a new folder in the current working directory   

In [295]:
help(os.makedirs)

Help on function makedirs in module os:

makedirs(name, mode=511, exist_ok=False)
    makedirs(name [, mode=0o777][, exist_ok=False])

    Super-mkdir; create a leaf directory and all intermediate ones.  Works like
    mkdir, except that any intermediate path segment (not just the rightmost)
    will be created if it does not exist. If the target directory already
    exists, raise an OSError if exist_ok is False. Otherwise no exception is
    raised.  This is recursive.



In [296]:
'data' in os.listdir()   # it will check if the new folder is created or not in the current working directory

True

In [ ]:
os.listdir()  #data folder add karne time new_file,new_folder bhi add kar diya tha abb kernal reset karna hoga ye chize reset karne ke liye , even original folder me bhi save ho gya h

In [ ]:
import urllib.request 

In [ ]:
url1= "https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/loan1.csv"  
url2= "https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/loan2.csv"
url3= "https://raw.githubusercontent.com/aditya08xyz/practise-csv-file/refs/heads/main/loan3.csv"                                                                         

In [ ]:
urllib.request.urlretrieve(url1, './data/loan1.txt')   # it will download the file from the url and save it in the data folder with the name loan1.txt

('./data/loan1.txt', <http.client.HTTPMessage at 0x201f8a1c160>)

In [ ]:
urllib.request.urlretrieve(url2, './data/loan2.txt')

('./data/loan2.txt', <http.client.HTTPMessage at 0x201f87c6a50>)

In [ ]:
urllib.request.urlretrieve(url3, './data/loan3.txt')

('./data/loan3.txt', <http.client.HTTPMessage at 0x201f7deda90>)

In [ ]:
os.listdir('./data')

['emis2.txt', 'loan1.txt', 'loan2.txt', 'loan3.txt']

In [ ]:
file1 = open('./data/loan1.txt', mode='r')  # r=read , w=write (if data exist then the data wipes out for fresh writing and w mostly use while creating new file) , a=append , b=binary(for images) , t=text

In [ ]:
file1_contents = file1.read()   # it will read the whole file and store it in the variable file1_contents

In [ ]:
file1_contents

In [ ]:
print(file1_contents)     # usially we get the string output here with/n so the print function helps with proper format output

In [ ]:
file1.close()     #important to close the file as if we are reading a larger file it may take a lot of memory and hang

In [ ]:
file1.read()   # now itll not open 

In [ ]:
# shortcut for open and close - python syntax
with open('./data/loan2.txt', 'r') as file2:           #it authomatically closes the file 
    file2_contents= file2.read()
    print(file2_contents)


In [ ]:
file2.read()   # file is closed and u cannot read it now, if u want to read it again u have to open it again with open() function, but u can check the content inside 

In [ ]:
with open('./data/loan3.txt', 'r') as file3:
    file3_lines = file3.readlines()   # it will read the file line by line and store it in the variable file3_lines as a list of strings

NOTE if some file is in WITH OPEN then u cant separetely use read or write function in any other code cell , u can use the name of variable its inside in 

In [ ]:
file3_lines

In [ ]:
file3_lines[2].strip()  # it will remove the leading and trailing whitespaces from the string

In [ ]:
print(file2_contents)      # duration is in MONTHS and rate is ANNUALLY 

#####now now we have to arrNGE ALL THE DATA IN (LIST OF DICTIONARIES) ---NOW THE  REAL PAIN IN ASS STARTS :(    ############################################################################


In [ ]:
def parse_headers(header_line):
    return header_line.strip().split(',')       #it will take the value of any row of a csv file and remove /n and arrange them in a good manner like seprated with commas and all


In [ ]:
# eg
headers = parse_headers(file3_lines[0])  # here we are using the above function to create a perfect headers(we use file3_lines[0]) for us like the amount, rate, duration and all that ll help us later to arrange the data 
headers

In [ ]:
# to get the the float values that will assign those headers 
def parse_values(data_line):
    values=[]                                    # here data_line can be anything like file3_lines[2]
    for item in data_line.strip().split(','):
        if item == '':                            # we are using this function to take a clear value without/n and in float value so that if any thing like downpayment is zero , so the function must not fail , it say 0.0 as written in if statement, called handling missing values
            values.append(0.0)
        else:
            values.append(float(item))
    return values

In [ ]:
#eg
parse_values(file3_lines[1])

In [ ]:
def create_item_dict(values, headers):
    result = {}
    for value, header in zip(values, headers):         # zip pairs the value alternate of each other like names= aditya,ujjwal no.=10,20   so if i use zip(name,no.)= (aditya,10),(ujjwal,20)
        result[header] = value     #important # since in dictionaries we cant append cuz it has key and value we cant append it like result.append(value,header) instead we use result[key] = value
    return result  

In [ ]:
values1 = parse_values(file3_lines[1])
values1

In [ ]:
headers

In [ ]:
create_item_dict(values1, headers)

In [ ]:
#another quick example
values2 = parse_values(file3_lines[2])
create_item_dict(values2, headers)

In [ ]:
def read_csv(path):
    result=[]
    #open the file in read mode
    with open(path, 'r') as f:
        #get the list of lines
        lines = f.readlines()
        # parse the headers
        headers = parse_headers(lines[0])
        
        for data_line in lines[1:]:
            #parse the values
            values = parse_values(data_line)
            # create a dictionary using values & headers
            item_dict = create_item_dict(values,headers)
            result.append(item_dict)
    return result

In [ ]:
with open('./data/loan3.txt') as file3:
    print(file3.read())

amount,duration,rate,down_payment
400000,12,11.0,40000
500000,24,11.5,50000
600000,36,12.0,60000
750000,48,12.5,75000
900000,60,13.0,90000



In [ ]:
read_csv('./data/loan3.txt')

#SUMMARY

In [ ]:
def parse_headers(header_line):
    return header_line.strip().split(',')

def parse_values(data_lines):
    values= []
    for item in data_lines.strip().split(','):
        if item == '':
            values.append(0.0)
        else:
            values.append(float(item))
    return values

def create_item_dict(values, headers):
    result = {}
    for value,header in zip(values, headers):
        result[header]=value
    return result

def read_csv(path):
    result = []                          # {}is use for dictionaries and [] is use for lists and u can only append lists not dictionaries so we ve used [] .
    with open(path, 'r') as f:
        lines= f.readlines()
        headers = parse_headers(lines[0])
        for data_line in lines[1:]:
            values=parse_values(data_line)
            item_dict=create_item_dict(values, headers)
            result.append(item_dict)
    return(result)

In [ ]:
read_csv('./data/loan2.txt')

[{'amount': 50000.0, 'duration': 6.0, 'rate': 7.5, 'down_payment': 5000.0},
 {'amount': 75000.0, 'duration': 12.0, 'rate': 8.0, 'down_payment': 7500.0},
 {'amount': 125000.0, 'duration': 18.0, 'rate': 8.75, 'down_payment': 12500.0},
 {'amount': 175000.0, 'duration': 24.0, 'rate': 9.25, 'down_payment': 17500.0},
 {'amount': 225000.0, 'duration': 36.0, 'rate': 9.75, 'down_payment': 22500.0}]

In [ ]:
import math                 #now remember the previous notebook on calculating emi's , defining function on emi
def loan_emi(amount, duration, rate, down_payment=0):
    loan_amount= amount - down_payment
    try:
        emi = loan_amount * rate * (1+rate)**duration / ((1+rate)**duration - 1)
    except ZeroDivisionError:
        emi = loan_amount/duration
    emi = math.ceil(emi)
    return emi

In [ ]:
loan2=read_csv('./data/loan2.txt')
loan2

[{'amount': 50000.0, 'duration': 6.0, 'rate': 7.5, 'down_payment': 5000.0},
 {'amount': 75000.0, 'duration': 12.0, 'rate': 8.0, 'down_payment': 7500.0},
 {'amount': 125000.0, 'duration': 18.0, 'rate': 8.75, 'down_payment': 12500.0},
 {'amount': 175000.0, 'duration': 24.0, 'rate': 9.25, 'down_payment': 17500.0},
 {'amount': 225000.0, 'duration': 36.0, 'rate': 9.75, 'down_payment': 22500.0}]

In [ ]:
# adding emi in loan2
for loan in loan2:
    loan['emi'] = loan_emi(loan['amount'],loan['duration'],loan['rate']/100/12,loan['down_payment'])     #since rate was yearly , for emi convert it into monthly . rate = 7.5% = 7.5/100 annually = 7.5/100/12 monthly
# bro the basic concept of list of dictionaries used here , if u cant understand pls use chatgtp and do some practise  eg- in this when i say loan in loan2 , loan= means all the dict inside the list ,now loan refers the dict inside the list , so laon['amount']= all the diff amounts , if i said loan[amount]/2 that changes the value of amounts in loan2 

In [ ]:
loan2

[{'amount': 50000.0,
  'duration': 6.0,
  'rate': 7.5,
  'down_payment': 5000.0,
  'emi': 7665},
 {'amount': 75000.0,
  'duration': 12.0,
  'rate': 8.0,
  'down_payment': 7500.0,
  'emi': 5872},
 {'amount': 125000.0,
  'duration': 18.0,
  'rate': 8.75,
  'down_payment': 12500.0,
  'emi': 6692},
 {'amount': 175000.0,
  'duration': 24.0,
  'rate': 9.25,
  'down_payment': 17500.0,
  'emi': 7214},
 {'amount': 225000.0,
  'duration': 36.0,
  'rate': 9.75,
  'down_payment': 22500.0,
  'emi': 6511}]

In [ ]:
for loan in loan2:
    loan['amount']= loan['amount']/2   #this code cell is just for example :)
print(loan2)

[{'amount': 25000.0, 'duration': 6.0, 'rate': 7.5, 'down_payment': 5000.0, 'emi': 28124}, {'amount': 37500.0, 'duration': 12.0, 'rate': 8.0, 'down_payment': 7500.0, 'emi': 44999}, {'amount': 62500.0, 'duration': 18.0, 'rate': 8.75, 'down_payment': 12500.0, 'emi': 82031}, {'amount': 87500.0, 'duration': 24.0, 'rate': 9.25, 'down_payment': 17500.0, 'emi': 121406}, {'amount': 112500.0, 'duration': 36.0, 'rate': 9.75, 'down_payment': 22500.0, 'emi': 164531}]


now we were only playing with loan2 , so now lets make it user defined

In [ ]:
def compute_emis(loanX):   #loanX can be loan1,loan2,......
    for loan in loanX:
        loan['emi']=loan_emi(loan['amount'],loan['duration'],loan['rate']/100/12,loan['down_payment'])

In [ ]:
loan1=read_csv('./data/loan1.txt')

In [ ]:
compute_emis(loan1)   #note= compute_emis function is just adding the emis in dictionaries of any loan list like loan1 loan2 , so we dont have to manually put in using above method 

In [ ]:
#now to see that compute_emis function have done its work or not we ve to check it by calling
loan1

[{'amount': 100000.0,
  'duration': 12.0,
  'rate': 8.5,
  'down_payment': 10000.0,
  'emi': 7850},
 {'amount': 150000.0,
  'duration': 18.0,
  'rate': 9.0,
  'down_payment': 15000.0,
  'emi': 8046},
 {'amount': 200000.0,
  'duration': 24.0,
  'rate': 9.5,
  'down_payment': 20000.0,
  'emi': 8265},
 {'amount': 250000.0,
  'duration': 30.0,
  'rate': 10.0,
  'down_payment': 25000.0,
  'emi': 8508},
 {'amount': 300000.0,
  'duration': 36.0,
  'rate': 10.5,
  'down_payment': 30000.0,
  'emi': 8776}]

In [ ]:
print(loan1)  # for horizontal output

[{'amount': 100000.0, 'duration': 12.0, 'rate': 8.5, 'down_payment': 10000.0, 'emi': 7850}, {'amount': 150000.0, 'duration': 18.0, 'rate': 9.0, 'down_payment': 15000.0, 'emi': 8046}, {'amount': 200000.0, 'duration': 24.0, 'rate': 9.5, 'down_payment': 20000.0, 'emi': 8265}, {'amount': 250000.0, 'duration': 30.0, 'rate': 10.0, 'down_payment': 25000.0, 'emi': 8508}, {'amount': 300000.0, 'duration': 36.0, 'rate': 10.5, 'down_payment': 30000.0, 'emi': 8776}]


In [ ]:
#now lets create a file in data 
with open('./data/emis2.txt', 'w') as f:      # 'w' insures a create a clean place to write if the file is already exist then i wipes all the data else it create a seperate file 
    for loan in loan2:
        f.write('{},{},{},{},{}\n' .format(
                     loan['amount'],
                     loan['duration'],
                     loan['rate']/100/12,
                     loan['down_payment'],
                     loan['emi']
                  ))

In [241]:
loan2

[{'amount': 50000.0,
  'duration': 6.0,
  'rate': 7.5,
  'down_payment': 5000.0,
  'emi': 7665},
 {'amount': 75000.0,
  'duration': 12.0,
  'rate': 8.0,
  'down_payment': 7500.0,
  'emi': 5872},
 {'amount': 125000.0,
  'duration': 18.0,
  'rate': 8.75,
  'down_payment': 12500.0,
  'emi': 6692},
 {'amount': 175000.0,
  'duration': 24.0,
  'rate': 9.25,
  'down_payment': 17500.0,
  'emi': 7214},
 {'amount': 225000.0,
  'duration': 36.0,
  'rate': 9.75,
  'down_payment': 22500.0,
  'emi': 6511}]

In [ ]:
print('./data/loan2.txt')  # or open it using WIth open function  # while opening the output link u can see the directory loan2 doesnt have emi but locally it has so we need to secure it in directory

./data/loan2.txt


In [ ]:
os.listdir('data')    # u can see we did it we made a file , so like we took loan files calculate emis using defining function and then we made a physical file out of it with emi data in it........... yo crazy....... so we made a folder using os.makedir() funct in that we did alot of thing from abovr till now

['emis2.txt', 'loan1.txt', 'loan2.txt', 'loan3.txt']

In [297]:
os.listdir()

['.ipynb_checkpoints',
 'climate.txt',
 'data',
 'jupyter 1 ,basic python.ipynb',
 'jupyter 2 , start with numpy.ipynb',
 'new_file',
 'new_folder']

In [ ]:
os.listdir('data')      # lesgooooo//.......

['emis2.txt', 'loan1.txt', 'loan2.txt', 'loan3.txt']

In [300]:
with open('./data/emis2.txt') as f:     # note- if u dont mention r or w it will autumatically take the read mode
    print(f.read())

50000.0,6.0,0.0062499999999999995,5000.0,7665
75000.0,12.0,0.006666666666666667,7500.0,5872
125000.0,18.0,0.007291666666666666,12500.0,6692
175000.0,24.0,0.0077083333333333335,17500.0,7214
225000.0,36.0,0.008125,22500.0,6511



#now let make a function to do the same and making more emis file in data folder

In [322]:
def write_csv(items, path):
    #open the file in write mode
    with open(path, 'w') as f:
        if len(items) == 0:  #return if theres nothing to write
            return
        
        #write a header in the first line                   #even i didnt understand this code , let focus on its working
        headers = list(items[0].keys())
        f.write(','.join(headers) + '\n')

        #write one item per line
        for item in items:
            values = []
            for header in headers:
                values.append(str(item.get(header,"")))
            f.write(','.join(values) + "\n")

In [ ]:
loan3 = read_csv('./data/loan3.txt')

In [313]:
compute_emis(loan3)

In [323]:
write_csv(loan3, './data/emis3.txt')

In [324]:
with open('./data/emis3.txt') as f:
    print(f.read())

amount,duration,rate,down_payment,emi
400000.0,12.0,11.0,40000.0,31818
500000.0,24.0,11.5,50000.0,21079
600000.0,36.0,12.0,60000.0,17936
750000.0,48.0,12.5,75000.0,17942
900000.0,60.0,13.0,90000.0,18430



In [ ]:
os.listdir('data')     #we made another physical file 

['emis2.txt', 'emis3.txt', 'loan1.txt', 'loan2.txt', 'loan3.txt']

In [332]:
for i in range(1,4):
    loan = read_csv('./data/loan{}.txt'.format(i))
    compute_emis(loan)                                  
    write_csv(loan, './data/emis{}.txt'.format(i))

In [334]:
os.listdir('data')    #so it dont make the same existing file twice , even after runnung the just above code for multiple times

['emis1.txt', 'emis2.txt', 'emis3.txt', 'loan1.txt', 'loan2.txt', 'loan3.txt']